name: Build Binaries

on:
    push:
        branches:
            - main

jobs:
    build-windows-binary:
        runs-on: windows-latest

        steps:

            - name: 'Checkout'
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: Install dependencies
              run: pip install -r src/requirements.txt

            - name: Build Windows binary
              run: pyinstaller --onefile -w src/vatservice.py

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                    name: windows-binary
                    path: dist/vatservice-gui.exe

    build-linux-binary:
        runs-on: ubuntu-latest
        steps:

            - name: 'Checkout'
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: Install dependencies
              run: pip install -r src/requirements.txt

            - name: Build Linux binary
              run: pyinstaller --onefile src/vatservice.py

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                    name: linux-binary
                    path: dist/vatservice-gui