name: Build Binaries

on:
    push:
      tags:
        - 'v*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build-windows-binary:
      needs: create-release
      runs-on: windows-latest

      steps:

          - name: 'Checkout'
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.12

          - name: Install dependencies
            run: pip install -r src/requirements.txt

          - name: Build Windows binary
            run: pyinstaller --onefile -w src/vatservice.py -n vatservice-gui-windows.exe

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                  name: vatservice-gui-windows.exe
                  path: dist/vatservice-gui-windows.exe   

  build-linux-binary:
      needs: create-release
      runs-on: ubuntu-latest
      steps:

          - name: 'Checkout'
            uses: actions/checkout@v4

          - name: Install dependencies
            run: sudo apt-get install build-essential libgtk-3-dev

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.12

          - name: Install dependencies
            run: pip install -r src/requirements.txt

          - name: Build Linux binary
            run: pyinstaller --onefile src/vatservice.py -n vatservice-gui-linux

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: vatservice-gui-linux
              path: dist/vatservice-gui-linux

  deploy:
    runs-on: ubuntu-latest
    needs: [create-release, build-windows-binary, build-linux-binary]
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: vatservice-gui-linux

        - uses: actions/download-artifact@v4
          with:
            name: vatservice-gui-windows.exe

        - name: Upload Release Asset Linux
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.create-release.outputs.upload_url }} 
            asset_path: vatservice-gui-linux
            asset_name: vatservice-gui-linux-${{ github.ref }}
            asset_content_type: application/octet-stream

        - name: Upload Release Asset Windows
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.create-release.outputs.upload_url }} 
            asset_path: vatservice-gui-windows.exe
            asset_name: vatservice-gui-windows-${{ github.ref }}.exe
            asset_content_type: application/octet-stream            
